// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  Layout: {
    meta: {
      title: 'Verkron';
      description: 'Verkron provides expert solutions in pricing strategies, operations, inventory management, technical drafting, corporate branding, supply chain optimization, and industrial product design. Our goal is to enhance efficiency, drive innovation, and support businesses in achieving operational excellence.';
    };
    signIn: 'Sign in';
    signOut: 'Sign out';
    signOutError: 'Failed to sign out';
  };
};
export default messages;
